
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/recruit_db?useUnicode=true&characterEncoding=utf8&serverTimezone=Asia/Seoul
    username: root
    password: 1234
logging:
  level:
    com.example.recruit.mapper.*: DEBUG
mybatis:
  config-location: classpath:/mybatis/mybatis-config.xml
  mapper-locations: classpath:/mybatis/mapper/*
